#!/usr/bin/env python3
"""
analyze.py — read ALL accumulated data and write docs/INSIGHTS.md: per-strategy
performance (historical backtest + captured live games) plus condition
breakdowns (does edge size / quarter / side predict wins?). This is the doc the
user reviews with Claude before deciding any retune. Re-runnable; it regenerates
the data sections each time.

    python3 analyze.py

Add new variables to examine by extending `condition_breakdowns()`.
"""
import glob, json, os
from collections import defaultdict

import backtest
import strategies as strat

ROOT = os.path.dirname(os.path.abspath(__file__))
GAMES = os.path.join(ROOT, "data", "games")
INSIGHTS = os.path.join(ROOT, "docs", "INSIGHTS.md")


_LEAGUES = {"NBA", "WNBA", "NCAAM", "NCAAW", "NCAA"}


def league_of_gid(gid):
    """game_id is <date>_<LEAGUE>_<away>_<home> (new) or <date>_<away>_<home>
    (legacy, pre-multi-league = NBA)."""
    parts = (gid or "").split("_")
    if len(parts) >= 2 and parts[1] in _LEAGUES:
        return parts[1]
    return "NBA"


def _all_decisions(strategy_label=None):
    """Every closed paper decision across all captured games, each tagged with its
    game_id. Optionally filter to one strategy (by its label)."""
    out = []
    for p in glob.glob(os.path.join(GAMES, "*", "paper_decisions.jsonl")):
        gid = os.path.basename(os.path.dirname(p))
        for line in open(p):
            line = line.strip()
            if not line:
                continue
            try:                       # tolerate a partial line the daemon is mid-writing
                d = json.loads(line)
            except Exception:
                continue
            if d.get("event") != "close":
                continue
            if strategy_label and d.get("strategy") != strategy_label:
                continue
            d["_game_id"] = gid
            out.append(d)
    return out


def _bucket(edge):
    if edge is None:
        return "?"
    e = edge * 100
    if e < 6:   return "<6¢"
    if e < 10:  return "6–10¢"
    if e < 15:  return "10–15¢"
    return "15¢+"


def condition_breakdowns(decisions):
    """How outcomes vary by entry condition. Returns {dim: {bucket: stats}}."""
    dims = {"edge_at_entry": defaultdict(lambda: {"n": 0, "w": 0, "pnl": 0.0}),
            "quarter": defaultdict(lambda: {"n": 0, "w": 0, "pnl": 0.0}),
            "side": defaultdict(lambda: {"n": 0, "w": 0, "pnl": 0.0}),
            "league": defaultdict(lambda: {"n": 0, "w": 0, "pnl": 0.0})}
    for d in decisions:
        pnl = d.get("sim", {}).get("sim_pnl") or 0
        win = d.get("sim", {}).get("result") == "WIN"
        keys = {"edge_at_entry": _bucket((d.get("signal") or {}).get("edge")),
                "quarter": f"Q{(d.get('game') or {}).get('period', '?')}",
                "side": (d.get("side") or "?").upper(),
                "league": league_of_gid(d.get("_game_id"))}
        for dim, k in keys.items():
            a = dims[dim][k]
            a["n"] += 1; a["w"] += win; a["pnl"] += pnl
    return dims


def main():
    os.makedirs(os.path.dirname(INSIGHTS), exist_ok=True)
    # 1. historical backtest (Kalshi candles) — robustness across many games
    dataset = backtest.load_all()
    hist = backtest.run_suite(strat.make, list(strat.REGISTRY), dataset)
    backtest.record_suite(hist, len(dataset))     # refresh ledger over the CURRENT corpus

    # 2. captured live games (includes order flow → live-only strategies too)
    cap, n_cap = backtest.run_captured(list(strat.REGISTRY))
    decisions = _all_decisions()
    dims = condition_breakdowns(decisions)

    L = []
    L.append("# INSIGHTS — auto-generated by analyze.py")
    L.append("\n> Data sections regenerate on each run. Use this to review with "
             "Claude, then apply approved changes to `strategy_params.json` "
             "(version bump + changelog). Params version: "
             f"`{strat.params_version()}`.\n")

    L.append(f"## Historical backtest ({len(dataset)} games, net of fees+slippage)\n")
    L.append("| strategy | $/game | win% | profitable | worst |")
    L.append("|---|---|---|---|---|")
    for k, a in sorted(hist.items(), key=lambda x: -(x[1]['pnl'] / max(x[1]['games'], 1))):
        wl = a["wins"] + a["losses"]
        wr = a["wins"] / wl * 100 if wl else 0
        per = a["pnl"] / a["games"] if a["games"] else 0
        L.append(f"| {k} | {per:+.2f} | {wr:.0f}% | {a['profitable_games']}/{a['games']} | {a['worst']:+.2f} |")

    L.append(f"\n## Captured live games ({n_cap}) — includes real order flow\n")
    L.append("| strategy | $/game | win% | trades |")
    L.append("|---|---|---|---|")
    for k, a in sorted(cap.items(), key=lambda x: -(x[1]['pnl'] / max(x[1]['games'], 1))):
        wl = a["wins"] + a["losses"]
        wr = a["wins"] / wl * 100 if wl else 0
        per = a["pnl"] / a["games"] if a["games"] else 0
        L.append(f"| {k} | {per:+.2f} | {wr:.0f}% | {a['trades']} |")

    L.append(f"\n## Condition breakdowns (from {len(decisions)} captured trades)\n")
    for dim, buckets in dims.items():
        if not buckets:
            continue
        L.append(f"**by {dim.replace('_', ' ')}:**\n")
        L.append("| bucket | trades | win% | avg P&L |")
        L.append("|---|---|---|---|")
        for b, a in sorted(buckets.items()):
            wr = a["w"] / a["n"] * 100 if a["n"] else 0
            L.append(f"| {b} | {a['n']} | {wr:.0f}% | {a['pnl']/a['n']:+.2f} |" if a["n"] else "")
        L.append("")

    L.append("## Observations (Claude reviews/extends here)")
    L.append("- _Run `analyze.py` after each game; Claude reads this + proposes "
             "changes with the data behind them; user approves; apply to "
             "strategy_params.json._")
    L.append("- Known to watch: `flow_confirm`'s 'flow flipped' exit can fire too "
             "often and turn a hold into a scalp (seen in captured data).")

    open(INSIGHTS, "w").write("\n".join(L) + "\n")
    print(f"Wrote {INSIGHTS}")
    print(f"  historical: {len(dataset)} games | captured: {n_cap} games | "
          f"{len(decisions)} trades analyzed")


if __name__ == "__main__":
    main()
